Course6_Backend/Section1/LibraryManagementSystem/LibraryManagementSystem/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagementSystem.Models
{
    public class Book
    {
        /// <summary>
        /// 書號(BOOK_ID)
        /// </summary>
        ///[MaxLength(5)]
        [DisplayName("書號")]
        public int BookId { get; set; }

        /// <summary>
        /// 書名
        /// </summary>
        [DisplayName("書名")]
        //[Required(ErrorMessage = "此欄位必填")]
        public string BookName { get; set; }

        /// <summary>
        /// 作者
        /// </summary>
        [DisplayName("作者")]
        //[Required(ErrorMessage = "此欄位必填")]
        public string BookAuthor { get; set; }

        /// <summary>
        /// 出版商
        /// </summary>
        [DisplayName("出版商")]
        //[Required(ErrorMessage = "此欄位必填")]
        public string BookPublisher { get; set; }

        /// <summary>
        /// 內容簡介
        /// </summary>
        [MaxLength(1000, ErrorMessage = "限制字數需小於1000字")]
        [AllowHtml]
        [DisplayName("內容簡介")]
        //[Required(ErrorMessage = "此欄位必填")]
        public string BookNote { get; set; }

        /// <summary>
        /// 購書日期
        /// </summary>
        [DisplayName("購書日期")]
        //[Required(ErrorMessage = "此欄位必填")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime BookBoughtDate { get; set; }

        /// <summary>
        /// 圖書類別名稱
        /// </summary>
        [DisplayName("圖書類別名稱")]
        public string BookClassName { get; set; }
        /// <summary>
        /// 圖書類別
        /// </summary>
        [DisplayName("圖書類別")]
        //[Required(ErrorMessage = "此欄位必填")]
        public string BookClassId { get; set; }

        /// <summary>
        /// 借閱狀態名稱
        /// </summary>
        [DisplayName("借閱狀態名稱")]
        public string StatusName { get; set; }
        /// <summary>
        /// 借閱狀態
        /// </summary>
        [DisplayName("借閱狀態")]
        //[Required(ErrorMessage = "此欄位必填")]
        public string BookStatusId { get; set; }

        /// <summary>
        /// 借閱人名稱
        /// </summary>
        [DisplayName("借閱人名稱")]
        public string BookKeeperName { get; set; }
        /// <summary>
        /// 借閱人英文名
        /// </summary>
        [DisplayName("借閱人中文名")]
        public string BookKeeperCName { get; set; }
        /// <summary>
        /// 借閱人
        /// </summary>
        [DisplayName("借閱人")]
        public string BookKeeperId { get; set; }

        /// <summary>
        /// 購書金額
        /// </summary>
        [DisplayName("購書金額")]
        public string BookAmount { get; set; }

        /// <summary>
        /// 建立時間
        /// </summary>
        [DisplayName("建立時間")]
        public string CreateDate { get; set; }

        /// <summary>
        /// 建立使用者
        /// </summary>
        [DisplayName("建立使用者")]
        public string CreateUser { get; set; }

        /// <summary>
        /// 修改時間
        /// </summary>
        [DisplayName("修改時間")]
        public string ModifyDate { get; set; }

        /// <summary>
        /// 修改使用者
        /// </summary>
        [DisplayName("修改使用者")]
        public string ModifyUser { get; set; }
    }
}

Course6_Backend/Section1/LibraryManagementSystem/LibraryManagementSystem/Models/BookLendRecord.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LibraryManagementSystem.Models
{
    public class BookLendRecord
    {
        /// <summary>
        /// 書號(BOOK_ID)
        /// </summary>
        ///[MaxLength(5)]
        [DisplayName("書號")]
        public int BookId { get; set; }

        /// <summary>
        /// 借閱日期
        /// </summary>
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DisplayName("借閱日期")]
        public DateTime LendDate { get; set; }

        /// <summary>
        /// 借閱人員編號
        /// </summary>
        [DisplayName("借閱人員編號")]
        public string BookKeeperId { get; set; }

        /// <summary>
        /// 借閱人英文姓名
        /// </summary>
        [DisplayName("英文姓名")]
        public string BookKeeperName { get; set; }

        /// <summary>
        /// 借閱人中文姓名
        /// </summary>
        [DisplayName("中文姓名")]
        public string BookKeeperCName { get; set; }

    }
}

Course6_Backend/Section1/LibraryManagementSystem/LibraryManagementSystem/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryManagementSystem.Service;
using Newtonsoft.Json;

namespace LibraryManagementSystem.Controllers
{
    public class BookController : Controller
    {
        // 操作圖書資料Service
        private ICodeService codeService { get; set; }
        // 取得DropDownList的Text/Value
        private IBookService bookService { get; set; }

        /// <summary>
        /// 取得圖書類別的Text/Value
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetBookClassCodeData()
        {
            var result = this.codeService.GetBookClass();
            return this.Json(result);
        }


        /// <summary>
        /// 取得借閱人的Text/Value
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetBookKeeperCodeData()
        {
            var result = this.codeService.GetBookKeeper();
            return this.Json(result);
        }


        /// <summary>
        /// 取得借閱狀態的Text/Value
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetBookStatusCodeData()
        {
            var result = this.codeService.GetBookStatus();
            return this.Json(result);
        }


        /// <summary>
        /// 取得書名
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetBookNameData()
        {
            var result = this.bookService.GetBookIdNameData();
            return this.Json(result);
        }


        /// <summary>
        /// 圖書資料查詢畫面
        /// </summary>
        /// <returns></returns>
        // GET: Book
        public ActionResult Index()
        {
            // Log測試
            try
            {
                //int i, j;
                //i = 0;
                //j = 1 / i;
                 return View();   
            }
            catch (Exception ex)
            {
                LibraryManagementSystem.Common.Logger.Write(LibraryManagementSystem.Common.Logger.LogCategoryEnum.Error, ex.ToString());
                return View("Error");
            }
            
        }


        /// <summary>
        /// 查詢圖書資料
        /// </summary>
        /// <returns></returns>
        [HttpPost()]
        public JsonResult Index(LibraryManagementSystem.Model.BookSearchArg bookSearchArg)
        {
            // 以參數條件取得Book Data
            var result = this.bookService.GetBookDataByCondition(bookSearchArg);
            return this.Json(result);
        }


        /// <summary>
        /// 圖書明細資料畫面
        /// </summary>
        /// <param name="bookId"></param>
        /// <returns></returns>
        [HttpPost()]
        public JsonResult BookDetail(string bookId)
        {
            // bookId資料型態為int，須轉型
            var id = int.Parse(bookId);
            LibraryManagementSystem.Model.Book result = bookService.GetBookDetailById(id);
            return this.Json(result);
        }

        /// <summary>
        /// 圖書更新畫面(修改)
        /// </summary>
        /// <param name="bookId"></param>
        /// <returns></returns>
        [HttpGet()]
        public ActionResult UpdateBook(string bookId)
        {
            var id = int.Parse(bookId);
            LibraryManagementSystem.Model.Book result = bookService.GetBookDetailById(id);
            return View(result);
        }


        /// <summary>
        /// 更新(修改)圖書資料
        /// </summary>
        /// <param name="book"></param>
        /// <returns></returns>
        [HttpPost()]
        public JsonResult UpdateBook(LibraryManagementSystem.Model.Book book)
        {
            try { 
            LibraryManagementSystem.Model.Book origin = bookService.GetBookDetailById(book.BookId);
            // 若validation通過，才能更新圖書資料並返回Index頁面

                bookService.UpdateBookData(book, origin);
                return this.Json(new { status = true, message = "成功編輯：(" + book.BookId + ") " + book.BookName });
            }catch(Exception ex)
            {
                return this.Json(new { status = false, message = "編輯失敗" });
            }
        }


        /// <summary>
        /// 刪除圖書
        /// </summary>
        /// <param name="bookId"></param>
        /// <returns></returns>
        [HttpPost()]
        public JsonResult DeleteBook(string bookId)
        {
            var id = int.Parse(bookId);
            try
            {
                LibraryManagementSystem.Model.Book result = bookService.GetBookDetailById(id);
                // 若借閱狀態為B(已借出)或C(已借出未領)，不可刪除書籍
                if (result.BookStatusId == "B" || result.BookStatusId == "C")
                {
                    return this.Json(new { status = false, message = "本圖書已借出，無法刪除" });
                }
                else
                {
                    bookService.DeleteBookById(bookId);
                    return this.Json(new {status = true, message = "成功刪除：("+bookId+") "+result.BookName });
                }
            }
            catch (Exception ex)
            {
                // 不可直接回傳false
                return this.Json(false);
            }
        }


        /// <summary>
        /// 新增圖書畫面
        /// </summary>
        /// <returns></returns>
        [HttpGet()]
        public ActionResult InsertBook()
        {
            return View(new LibraryManagementSystem.Model.Book());
        }

        /// <summary>
        /// 新增圖書
        /// </summary>
        /// <param name="book"></param>
        /// <returns></returns>
        [HttpPost()]
        public JsonResult InsertBook(LibraryManagementSystem.Model.Book book)
        {
            try
            {
                int newBookId = 0;
                newBookId = bookService.InsertBook(book);
                return this.Json(new { status = true, message = "成功新增：(" + newBookId + ") " + book.BookName , newBookId = newBookId});
            }
            catch (Exception ex)
            {
                return this.Json(new { status = false, message = "新增失敗" });
            }            
        }


        /// <summary>
        /// 圖書借閱紀錄畫面
        /// </summary>
        /// <param name="bookId"></param>
        /// <returns></returns>
        [HttpPost()]
        public JsonResult BookLendRecord(string bookId)
        {
            var id = int.Parse(bookId);
            List<LibraryManagementSystem.Model.BookLendRecord> result = bookService.GetBookLendRecord(id);
            return this.Json(result);
        }
    }
}

Course6_Backend/Section1/LibraryManagementSystem/LibraryManagementSystem/Views/Book/BookDetail.cshtml
@model LibraryManagementSystem.Models.Book

@{
    ViewBag.Title = "圖書明細";
}

<h2>圖書明細</h2>

<div>
    <hr />
    <table class="table table-striped table-bordered">
        <tr>
            <th style="width:10%">
                @Html.DisplayNameFor(model => model.BookName)
            </th>

            <td>
                @Html.DisplayFor(model => model.BookName)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookAuthor)
            </th>

            <td>
                @Html.DisplayFor(model => model.BookAuthor)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookPublisher)
            </th>

            <td>
                @Html.DisplayFor(model => model.BookPublisher)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookNote)
                @*<div id="test"></div>*@                
            </th>

            <td>
                @Html.DisplayFor(model => model.BookNote)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookBoughtDate)
            </th>

            <td>
                @Html.DisplayFor(model => model.BookBoughtDate)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookClassId)
            </th>

            <td>
                @Html.DisplayFor(model => model.BookClassName)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookStatusId)
            </th>

            <td>
                @Html.DisplayFor(model => model.StatusName)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookKeeperId)
            </th>

            <td>
                @Html.DisplayFor(model => model.BookKeeperName)
            </td>
        </tr>
    </table>
</div>
<p>
    @Html.ActionLink("回上頁", "Index")
</p>
@*<script>
    $("#test").html('@Html.Raw(@Model.BookNote)');
</script>*@

Course6_Backend/Section1/LibraryManagementSystem/LibraryManagementSystem/Views/Book/BookLendRecord.cshtml
@model IEnumerable<LibraryManagementSystem.Models.BookLendRecord>

@{
    ViewBag.Title = "圖書借閱紀錄";
}

<h2>圖書借閱紀錄</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LendDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookKeeperId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookKeeperName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookKeeperCName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LendDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookKeeperId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookKeeperName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookKeeperCName)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>*@
        </tr>
    }

</table>

<div>
    @Html.ActionLink("回上頁", "Index")
</div>

Course6_Backend/Section1/LibraryManagementSystem/LibraryManagementSystem/Views/Book/Index.cshtml
@{
    ViewBag.Title = "首頁";
}

<h2>圖書查詢</h2>

<div class="form-horizontal">
    @*新增編輯刪除是否成功資訊*@
    <div style="text-align: center;" id="msg"></div>
    <br />
    @*圖書搜尋欄位(Index)*@
    <div class="form-group">
        <label class="control-label col-md-1" , style="text-align:left">書名</label>
        <div class="col-md-10">
            @*書名*@
            <input style="width:40%" id='BookName' />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-1" , style="text-align:left">圖書類別</label>
        <div class="col-md-10">
            @*圖書類別*@
            <select style="width:40%" id="BookClassId"></select>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-1" , style="text-align:left">借閱人</label>
        <div class="col-md-10">
            @*借閱人*@
            <select style="width:40%" id="BookKeeperId"></select>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-1" , style="text-align:left">借閱狀態</label>
        <div class="col-md-10">
            @*借閱狀態*@
            <select style="width:40%" id="BookStatusId"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-1">
        </div>
        <div class="col-md-10">
            @*查詢*@
            <input id="BookSearch" class="btn btn-primary" type="submit" value="查詢" />
            @*清除*@
            <input id="ClearSearchArg" class="btn btn-default" type="button" value="清除" />
            @*新增*@
            <input id="InsertBookWindow" class="btn btn-link" type="button" value="新增" />
        </div>
    </div>

    @* 查詢結果kendoGrid *@
    <div id="BookSearchResult"></div>

</div>

@* 借閱紀錄kendoWindow *@
<div id="BookLendRecordWindow">
    <div id="BookLendRecordGrid"></div>
</div>

@* 新增、編輯、明細kendoWindow *@
<div class="uk-card uk-text-left" id="BookDataWindow" style="display:none; margin:0 auto; width: 100%">
    <form id="BookDataForm">
        <table Align="center">
            <tr>

                <td>
                    <ul class="fieldlist" >
                        <li style="display:none">
                            <label>圖書編號</label>
                            @*TODO:更改name、id*@
                            <input id="BookIdData" name="book id" type="text" class="k-textbox"
                                   style="width: 100%;" />
                        </li>
                        <li>
                            <label>書名</label><br />
                            <input id="BookNameData" name="book name" type="text" class="k-textbox bookdata-text"
                                   style="width: 100%;" required />
                        </li>
                        <li>
                            <label>作者</label><br />
                            <input id="BookAuthorData" name="book author" type="text" class="k-textbox bookdata-text"
                                   style="width: 100%;" required />
                        </li>
                        <li>
                            <label>出版商</label><br />
                            <input id="BookPublisherData" name="book publisher" type="text" class="k-textbox bookdata-text"
                                   style="width: 100%;" required />
                        </li>
                        <li>
                            <label>內容簡介</label><br />
                            <textarea class="bookdata-text" id="BookNoteData" name="book note" style="width: 100%;" required data-max-msg="字數限制1000字"></textarea>
                            <div class="k-form-footer">
                                <div class="k-counter-container"><span class="k-counter-value">0</span>/1000</div>
                            </div>
                        </li>
                        <li>
                            <label>購買日期</label>
                            <input id="BookBoughtDateData" name="book bought date" value="2011-10-10"
                                   title="datepicker" style="width: 100%" required />
                        </li>
                        <li>
                            <label>圖書類別</label>
                            <select class="bookdata-dropdownlist" id="BookClassData" style="width: 100%;" required>
                            </select>
                        </li>
                        <li class="bookdata-column" id="BookStatusColumn" style="display:none">
                            <label>借閱狀態</label>
                            <select class="bookdata-dropdownlist" id="BookStatusData" style="width: 100%;" required>
                            </select>
                        </li>
                        <li class="bookdata-column" id="BookKeeperColumn" style="display:none">
                            <label>借閱人</label>
                            <select class="bookdata-dropdownlist" id="BookKeeperData" style="width: 100%;">
                            </select>
                        </li>

                        <li Align="center">
                            <button id="InsertBook" class="k-button k-primary btn-add-book bookdata-submit">新增</button>
                            <button id="UpdateBook" style="display:none" class="k-button k-primary btn-add-book bookdata-submit">存檔</button>
                        </li>
                    </ul>
                </td>
            </tr>
        </table>
    </form>

</div>
<style>
    .k-form-footer {
        display: flex;
        flex-direction: column;
    }

    .k-counter-container {
        color: #9C9C9C;
        font-size: 13px;
        margin-top: 5px;
        margin-left: auto;
    }
</style>

<script src="~/Scripts/BookScripts/Index.js"></script>

Course6_Backend/Section1/LibraryManagementSystem/LibraryManagementSystem/Views/Book/UpdateBook.cshtml
@model LibraryManagementSystem.Models.Book

@{
    ViewBag.Title = "圖書編輯";
}

<h2>圖書編輯</h2>

@using (Html.BeginForm("UpdateBook", "Book", FormMethod.Post, new { id = "Form2" }))
{
    @Html.AntiForgeryToken()

    <div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BookId)
        <table class="table table-striped table-bordered" style="width:50%">
            <tr>
                <td style="width:30%">
                    @Html.LabelFor(model => model.BookName, htmlAttributes: new { @class = "control-label col-md-10" })
                </td>

                <td>
                    @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BookName, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.BookAuthor, htmlAttributes: new { @class = "control-label col-md-10" })
                </td>

                <td>
                    @Html.EditorFor(model => model.BookAuthor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BookAuthor, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.BookPublisher, htmlAttributes: new { @class = "control-label col-md-10" })
                </td>

                <td>
                    @Html.EditorFor(model => model.BookPublisher, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BookPublisher, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.BookNote, htmlAttributes: new { @class = "control-label col-md-10" })
                </td>

                <td>
                    @Html.TextAreaFor(model => model.BookNote, 15, 80, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BookNote, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.BookBoughtDate, htmlAttributes: new { @class = "control-label col-md-10" })
                </td>

                <td>
                    @Html.TextBoxFor(model => model.BookBoughtDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "Date", @style = "text-align:left" })
                    @Html.ValidationMessageFor(model => model.BookBoughtDate, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.BookClassId, htmlAttributes: new { @class = "control-label col-md-10" })
                </td>

                <td>
                    @Html.DropDownListFor(model => model.BookClassId, (List<SelectListItem>)ViewBag.BookClassCodeData, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BookClassId, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.BookStatusId, htmlAttributes: new { @class = "control-label col-md-10" })
                </td>

                <td>
                    @Html.DropDownListFor(model => model.BookStatusId, (List<SelectListItem>)ViewBag.BookStatusCodeData, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BookStatusId, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.BookKeeperId, htmlAttributes: new { @class = "control-label col-md-10" })
                </td>

                <td>
                    @Html.DropDownListFor(model => model.BookKeeperId, (List<SelectListItem>)ViewBag.BookKeeperCodeData, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BookKeeperId, "", new { @class = "text-danger" })
                </td>
            </tr>
        </table>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="btnUpdate" type="submit" value="存檔" class="btn btn-primary" />
                <a class="btnDelete btn btn-danger" href="#" onclick="test(this, '@Model.BookId');">刪除</a>
                <input class="hidBookId" type="hidden" value='@Model.BookId' />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回上頁", "Index")
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var originBookKeeperId = $("#BookKeeperId").val();

        if ($("#BookStatusId").val() == "A" || $("#BookStatusId").val() == "U") {
            $("#BookKeeperId").attr('disabled', 'disabled');
            $("#BookKeeperId").val("");
            originBookKeeperId = "";
        }
        else {
            $("#BookKeeperId").removeAttr("disabled");
        }


        $("#BookStatusId").on("change", function () {
            if ($("#BookStatusId").val() == "A" || $("#BookStatusId").val() == "U") {
                $("#BookKeeperId").attr('disabled', 'disabled');
                $("#BookKeeperId").val("");
            }
            else {
                $("#BookKeeperId").removeAttr("disabled");
                $("#BookKeeperId").val(originBookKeeperId);
            }

        });

        $("#btnUpdate").click(function (e) {
            if ($("#BookStatusId").val() == "B" && $("#BookKeeperId").val() == 0) {
                alert("借閱狀態為：已借出，請輸入借閱人");
                return false;
            }
            if (!confirm("是否確定更新？")) {
                return false;
            }
        });

        $(".btnDelete").click(function (e) {
            e.preventDefault();
            var tr = $(this).closest('tr');
            var bookId = $(this).next().val();
            if (confirm("是否刪除編號（" + bookId + "）之圖書？")) {
                $.ajax({
                    type: "POST",
                    url: "/Book/DeleteBook",
                    data: "bookId=" + $(this).next().val(),
                    dataType: "json",
                    success: function (response) {
                        if (response) {
                            $(tr).remove();
                            alert("已刪除編號（" + bookId + "）之圖書");
                            window.location.replace("/Book/Index");
                        }
                        else {
                            alert("本圖書已借出，無法刪除");
                        }

                    }, error: function (error) {
                        alert("系統發生錯誤，刪除失敗");
                    }
                });
            }
            return false;
        });
    });
</script>